///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TradeTrackerProject.TestCases.ShopOtherOptions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VisitOtherShopOptions recording.
    /// </summary>
    [TestModule("5ef077c1-78f8-4350-84d1-75b98ff7b614", ModuleType.Recording, 1)]
    public partial class VisitOtherShopOptions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TradeTrackerProject.TradeTrackerProjectRepository repository.
        /// </summary>
        public static TradeTrackerProject.TradeTrackerProjectRepository repo = TradeTrackerProject.TradeTrackerProjectRepository.Instance;

        static VisitOtherShopOptions instance = new VisitOtherShopOptions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VisitOtherShopOptions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VisitOtherShopOptions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(0));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1, ShopsList_validation_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(1));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(2));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1, Shop_Info_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            ConstantUserCode.UserCodeCollection.displayShopFascia();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'PkComTradetracker'.", repo.PkComTradetracker.SelfInfo, new RecordItemIndex(4));
            repo.PkComTradetracker.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(5));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_2, ShopsList_validation_Screenshot1_2_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(6));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(7));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_2, Shop_Info_Screenshot1_2_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetails' at Center", repo.PkComTradetracker.ShopDetailsInfo, new RecordItemIndex(8));
            repo.PkComTradetracker.ShopDetails.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(9));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_3, Shop_Info_Screenshot1_3_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetail_ProceedButton' at Center", repo.PkComTradetracker.ShopDetail_ProceedButtonInfo, new RecordItemIndex(10));
            repo.PkComTradetracker.ShopDetail_ProceedButton.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.checkShopVisited();
            Delay.Milliseconds(0);
            
            ConstantUserCode.UserCodeCollection.validateTradeTracker();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn' at Center", repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckInInfo, new RecordItemIndex(13));
            repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.CheckIn_ListView();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.ShopOptions_ListView'.", repo.PkComTradetracker.ShopOptions_ListViewInfo, new RecordItemIndex(15));
            Validate.Exists(repo.PkComTradetracker.ShopOptions_ListViewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List3.ShopClosed' at Center", repo.PkComTradetracker.List3.ShopClosedInfo, new RecordItemIndex(16));
            repo.PkComTradetracker.List3.ShopClosed.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.Validate_CameraScreen'.", repo.PkComTradetracker.Validate_CameraScreenInfo, new RecordItemIndex(17));
            Validate.Exists(repo.PkComTradetracker.Validate_CameraScreenInfo);
            Delay.Milliseconds(0);
            
            ConstantUserCode.UserCodeCollection.TakePhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.TPOSM_ButtonDone' at Center", repo.PkComTradetracker.TPOSM_ButtonDoneInfo, new RecordItemIndex(19));
            repo.PkComTradetracker.TPOSM_ButtonDone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(20));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_3, ShopsList_validation_Screenshot1_3_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(21));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(22));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_4, Shop_Info_Screenshot1_4_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetails' at Center", repo.PkComTradetracker.ShopDetailsInfo, new RecordItemIndex(23));
            repo.PkComTradetracker.ShopDetails.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(24));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_5, Shop_Info_Screenshot1_5_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetail_ProceedButton' at Center", repo.PkComTradetracker.ShopDetail_ProceedButtonInfo, new RecordItemIndex(25));
            repo.PkComTradetracker.ShopDetail_ProceedButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(26));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.validateTradeTracker();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn' at Center", repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckInInfo, new RecordItemIndex(28));
            repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.CheckIn_ListView();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.ShopOptions_ListView'.", repo.PkComTradetracker.ShopOptions_ListViewInfo, new RecordItemIndex(30));
            Validate.Exists(repo.PkComTradetracker.ShopOptions_ListViewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List3.ShopPermanentlyClosed' at Center", repo.PkComTradetracker.List3.ShopPermanentlyClosedInfo, new RecordItemIndex(31));
            repo.PkComTradetracker.List3.ShopPermanentlyClosed.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.Validate_CameraScreen'.", repo.PkComTradetracker.Validate_CameraScreenInfo, new RecordItemIndex(32));
            Validate.Exists(repo.PkComTradetracker.Validate_CameraScreenInfo);
            Delay.Milliseconds(0);
            
            ConstantUserCode.UserCodeCollection.TakePhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.TPOSM_ButtonDone' at Center", repo.PkComTradetracker.TPOSM_ButtonDoneInfo, new RecordItemIndex(34));
            repo.PkComTradetracker.TPOSM_ButtonDone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(35));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_4, ShopsList_validation_Screenshot1_4_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(36));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(37));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_6, Shop_Info_Screenshot1_6_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetails' at Center", repo.PkComTradetracker.ShopDetailsInfo, new RecordItemIndex(38));
            repo.PkComTradetracker.ShopDetails.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(39));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_7, Shop_Info_Screenshot1_7_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetail_ProceedButton' at Center", repo.PkComTradetracker.ShopDetail_ProceedButtonInfo, new RecordItemIndex(40));
            repo.PkComTradetracker.ShopDetail_ProceedButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(41));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.validateTradeTracker();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn' at Center", repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckInInfo, new RecordItemIndex(43));
            repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.CheckIn_ListView();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.ShopOptions_ListView'.", repo.PkComTradetracker.ShopOptions_ListViewInfo, new RecordItemIndex(45));
            Validate.Exists(repo.PkComTradetracker.ShopOptions_ListViewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List3.ShopNotFound' at Center", repo.PkComTradetracker.List3.ShopNotFoundInfo, new RecordItemIndex(46));
            repo.PkComTradetracker.List3.ShopNotFound.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(47));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(48));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_5, ShopsList_validation_Screenshot1_5_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(49));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(50));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_8, Shop_Info_Screenshot1_8_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetails' at Center", repo.PkComTradetracker.ShopDetailsInfo, new RecordItemIndex(51));
            repo.PkComTradetracker.ShopDetails.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(52));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_9, Shop_Info_Screenshot1_9_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetail_ProceedButton' at Center", repo.PkComTradetracker.ShopDetail_ProceedButtonInfo, new RecordItemIndex(53));
            repo.PkComTradetracker.ShopDetail_ProceedButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(54));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.validateTradeTracker();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn' at Center", repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckInInfo, new RecordItemIndex(56));
            repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.CheckIn_ListView();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.ShopOptions_ListView'.", repo.PkComTradetracker.ShopOptions_ListViewInfo, new RecordItemIndex(58));
            Validate.Exists(repo.PkComTradetracker.ShopOptions_ListViewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List3.AreaClosed' at Center", repo.PkComTradetracker.List3.AreaClosedInfo, new RecordItemIndex(59));
            repo.PkComTradetracker.List3.AreaClosed.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.Validate_CameraScreen'.", repo.PkComTradetracker.Validate_CameraScreenInfo, new RecordItemIndex(60));
            Validate.Exists(repo.PkComTradetracker.Validate_CameraScreenInfo);
            Delay.Milliseconds(0);
            
            ConstantUserCode.UserCodeCollection.TakePhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.TPOSM_ButtonDone' at Center", repo.PkComTradetracker.TPOSM_ButtonDoneInfo, new RecordItemIndex(62));
            repo.PkComTradetracker.TPOSM_ButtonDone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(63));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_6, ShopsList_validation_Screenshot1_6_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(64));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(65));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_10, Shop_Info_Screenshot1_10_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetails' at Center", repo.PkComTradetracker.ShopDetailsInfo, new RecordItemIndex(66));
            repo.PkComTradetracker.ShopDetails.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(67));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_11, Shop_Info_Screenshot1_11_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetail_ProceedButton' at Center", repo.PkComTradetracker.ShopDetail_ProceedButtonInfo, new RecordItemIndex(68));
            repo.PkComTradetracker.ShopDetail_ProceedButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(69));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.validateTradeTracker();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn' at Center", repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckInInfo, new RecordItemIndex(71));
            repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.CheckIn_ListView();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.ShopOptions_ListView'.", repo.PkComTradetracker.ShopOptions_ListViewInfo, new RecordItemIndex(73));
            Validate.Exists(repo.PkComTradetracker.ShopOptions_ListViewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List3.ShopToBeRemoved' at Center", repo.PkComTradetracker.List3.ShopToBeRemovedInfo, new RecordItemIndex(74));
            repo.PkComTradetracker.List3.ShopToBeRemoved.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(75));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(76));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_7, ShopsList_validation_Screenshot1_7_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.FirstShopinShopList' at Center", repo.PkComTradetracker.FirstShopinShopListInfo, new RecordItemIndex(77));
            repo.PkComTradetracker.FirstShopinShopList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(78));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_12, Shop_Info_Screenshot1_12_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetails' at Center", repo.PkComTradetracker.ShopDetailsInfo, new RecordItemIndex(79));
            repo.PkComTradetracker.ShopDetails.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=105}) on item 'PkComTradetracker.Shop_Info'.", repo.PkComTradetracker.Shop_InfoInfo, new RecordItemIndex(80));
            Validate.ContainsImage(repo.PkComTradetracker.Shop_InfoInfo, Shop_Info_Screenshot1_13, Shop_Info_Screenshot1_13_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopDetail_ProceedButton' at Center", repo.PkComTradetracker.ShopDetail_ProceedButtonInfo, new RecordItemIndex(81));
            repo.PkComTradetracker.ShopDetail_ProceedButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ChangeOptionYesButton' at Center", repo.PkComTradetracker.ChangeOptionYesButtonInfo, new RecordItemIndex(82));
            repo.PkComTradetracker.ChangeOptionYesButton.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.validateTradeTracker();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn' at Center", repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckInInfo, new RecordItemIndex(84));
            repo.PkComTradetracker.ShopOpen_AndroidWidgetImageView_MapCheckIn.Touch();
            Delay.Milliseconds(500);
            
            ConstantUserCode.UserCodeCollection.CheckIn_ListView();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.ShopOptions_ListView'.", repo.PkComTradetracker.ShopOptions_ListViewInfo, new RecordItemIndex(86));
            Validate.Exists(repo.PkComTradetracker.ShopOptions_ListViewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List3.RetailerDidNotAllow' at Center", repo.PkComTradetracker.List3.RetailerDidNotAllowInfo, new RecordItemIndex(87));
            repo.PkComTradetracker.List3.RetailerDidNotAllow.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PkComTradetracker.Validate_CameraScreen'.", repo.PkComTradetracker.Validate_CameraScreenInfo, new RecordItemIndex(88));
            Validate.Exists(repo.PkComTradetracker.Validate_CameraScreenInfo);
            Delay.Milliseconds(0);
            
            ConstantUserCode.UserCodeCollection.TakePhoto();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.TPOSM_ButtonDone' at Center", repo.PkComTradetracker.TPOSM_ButtonDoneInfo, new RecordItemIndex(90));
            repo.PkComTradetracker.TPOSM_ButtonDone.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SHOP REMARKS') on item 'PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.SHOPREMARKS_validation'.", repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.SHOPREMARKS_validationInfo, new RecordItemIndex(91));
            Validate.AttributeEqual(repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.SHOPREMARKS_validationInfo, "Text", "SHOP REMARKS");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'PkComTradetracker'.", repo.PkComTradetracker.SelfInfo, new RecordItemIndex(92));
            repo.PkComTradetracker.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ValidateOKButton' at Center", repo.PkComTradetracker.ValidateOKButtonInfo, new RecordItemIndex(93));
            repo.PkComTradetracker.ValidateOKButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.DSRNotVisiting' at Center", repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.DSRNotVisitingInfo, new RecordItemIndex(94));
            repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.DSRNotVisiting.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.SchemeNotOffered' at Center", repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.SchemeNotOfferedInfo, new RecordItemIndex(95));
            repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.SchemeNotOffered.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.IncentiveNotPaid' at Center", repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.IncentiveNotPaidInfo, new RecordItemIndex(96));
            repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.IncentiveNotPaid.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.Others' at Center", repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.OthersInfo, new RecordItemIndex(97));
            repo.PkComTradetracker.ShopkeeperDidNotAllowRemarksListScreen.Others.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'PkComTradetracker'.", repo.PkComTradetracker.SelfInfo, new RecordItemIndex(98));
            repo.PkComTradetracker.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=480,Height=59}) on item 'PkComTradetracker.ShopsList_validation'.", repo.PkComTradetracker.ShopsList_validationInfo, new RecordItemIndex(99));
            Validate.ContainsImage(repo.PkComTradetracker.ShopsList_validationInfo, ShopsList_validation_Screenshot1_8, ShopsList_validation_Screenshot1_8_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage ShopsList_validation_Screenshot1
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_2
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_2
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_3
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_3_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_3
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_3_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_4
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_4_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_5
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_5_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_4
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_4_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_6
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_6_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_7
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_7_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_5
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_5_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_8
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_8_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_9
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_9_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_6
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_6_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_10
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_10_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_11
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_11_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_7
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_7_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_12
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_12_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Shop_Info_Screenshot1_13
        { get { return repo.PkComTradetracker.Shop_InfoInfo.GetScreenshot1(new Rectangle(0, 0, 480, 105)); } }

        Imaging.FindOptions Shop_Info_Screenshot1_13_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ShopsList_validation_Screenshot1_8
        { get { return repo.PkComTradetracker.ShopsList_validationInfo.GetScreenshot1(new Rectangle(0, 0, 480, 59)); } }

        Imaging.FindOptions ShopsList_validation_Screenshot1_8_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
